In [57]:
# ========== ----- ========== Import Libraries ========== ----- ========== #

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# from mlxtend.plotting import plot_decision_regions 

# ========== ----- ========== End ========== ----- ========== #

In [58]:
# ========== ----- ========== Import Dataset ========== ----- ========== #

# Read the CSV file into a pandas DataFrame
df = pd.read_csv('dataset.csv')
# Display the first few rows of the DataFrame
# df = df.drop('BMI', axis=1)
print(df.head())


# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    df.drop('Body_Level', axis=1), df['Body_Level'], test_size=0.2, random_state=42)

# Print the shapes of the training and test sets
print('Training set shape:', X_train.shape)
print('Test set shape:', X_test.shape)

# ========== ----- ========== End ========== ----- ========== #


   Body_Level  Gender       Age    Height    Weight  H_Cal_Consump  \
0           3       1  0.646666  0.690578  1.016135              1   
1           3       1 -0.649582 -0.003364  0.686578              1   
2           3       0 -0.537725  0.493657  1.790354              1   
3           3       0 -1.291128 -0.545353 -0.036499              1   
4           3       0  0.270463 -0.818715  0.951256              1   

   Veg_Consump  Water_Consump  Smoking  Meal_Count  ...  \
0    -0.199318       0.236558        0    0.402155  ...   
1     0.428856      -1.026715        0   -1.792121  ...   
2     1.069487       1.401741        0    0.402155  ...   
3     0.986227      -1.620907        0    0.402155  ...   
4     1.069487       0.974150        0    0.402155  ...   

   Food_Between_Meals_Always  Food_Between_Meals_Frequently  \
0                          0                              0   
1                          0                              0   
2                          0       

In [61]:
# ========== ----- ========== SVM Model ========== ----- ========== #

param_grid = {'C': [0.1, 1, 5, 10, 20, 30, 40, 50,
                    60, 70, 100, 200], 'gamma': [1, 0.1, 0.01, 0.001], 'kernel': ['linear', 'rbf', 'poly', 'sigmoid']}

model = svm.SVC()
grid = GridSearchCV(model, param_grid, refit=True)
grid.fit(X_train, y_train)
print(grid.best_estimator_)

# ========== ----- ========== End ========== ----- ========== #


SVC(C=5, gamma=1, kernel='linear')


In [62]:
# ========== ----- ========== Test SVM Model ========== ----- ========== #

# Predict the target variable for the test data
y_pred = grid.predict(X_test)

# Evaluate the model performance
accuracy = accuracy_score(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print('Accuracy:', accuracy)

# ========== ----- ========== End ========== ----- ========== #

[[ 41   0   0   0]
 [  2  41   0   0]
 [  0   3  82   0]
 [  0   0   0 127]]
Accuracy: 0.9831081081081081
